spring.application.name=gamezone

# Perfil utilizado al ejecutar el proyecto localmente
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Puerto de la aplicación
server.port=${PORT:8080}